application:
  title: RHitmo Hospede API
  version: 1.0.0


security:
  jwt:
    token:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

database:
  url: jdbc:postgresql://ep-steep-lake-168378.us-east-2.aws.neon.tech/
  banco: projetos
  username: yago.vcb
  password: ZgdvYMb4hj6D
  driver: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8051
  servlet:
    context-path: /api/v1
    encoding:
      charset: utf-8
      enabled: true

spring:
  application:
    name: rhitmo-hospede-api
  datasource:
    url: ${database.url}${database.banco}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: ${database.driver}
    hikari:
      pool-name: rhitmo-hospede-pool
      connection-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 600000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: ${database.dialect}
        show_sql: true
        hbm2ddl:
          auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    root: info
    web: debug
    sql: trace
    org.springframework: info
    org.hibernate: INFO